### PR TITLE
Make webri.ng more usable on mobile

### PR DESCRIPTION
**Pull request by sarajw**
Hiya! I've been using webri.ng while on the go a fair bit recently to edit the site list of the css joy webring, and if this change suits you, it would make it much easier for me to use on my mobile :)

Thanks!

### CODE REVIEW

**Comment by ajxs** [comment]
Thank you for putting in all this good work! I need to do much more to make the site responsive, and accessible. The overall design of the site was put together very quickly. If you have any ideas for how to improve the site's design in any way, please let me know! I wanted to keep it plain, and useful, but there's still much more room for things to be improved.

**Comment by sarajw** [comment]
Oooh I could be very tempted to play with the styling... I should probably try to get it to run locally though if I'm really going to dig in. Hm.

Mostly I'd be considering pumping the contrast a bit, and/or offering a light mode variant. It's pretty easy to have a site follow a viewer's OS dark/light mode settings with color-scheme

**Comment by ajxs** [comment]
The site is a bit tricky to run locally, unfortunately. The use of Docker makes running a local dev database, and mock mailserver easier.
My choice to go with server-side rendering was made because it tends to lead to faster loading times, and I could cut down on front-end complexity. The choice to use 'Pug' was made because it's one of the more popular, and full-featured template engines.
If it's easier, I'm happy to translate HTML to Pug, and integrate a design. I like people who contribute to get credit in the git history though. If I can help, just let me know.

**Comment by sarajw** [comment]
Oh ah, yes, I just looked closer at the ReadMe. And I see now that I edited the static (generated?) css file instead of the scss one - so I guess upon build it'd revert anyway?

Maybe I could set up a mock environment, with your HTML output, and the SCSS file. And then I'll just paste in SCSS changes via github's web UI...

**Comment by ajxs** [comment]
I actually missed that too. The meta tag addition works perfectly though.
That would work. If you can provide me the changes, I'm happy to put everything in Pug/SCSS.

**Comment by sarajw** [comment]
It's actually a good push to get me playing with SCSS, though I do think vanilla CSS is super powerful nowadays. Even nesting is turning up soon natively!

I've got a Sass compiler working now, and a hackily downloaded set of html files from your site. I'll have a play :)

**Pull request merged**
